#!/usr/bin/env python
import rospy
from human_moveit_config.human_model import HumanModel
import json
import rospkg
from baxter_commander.persistence import dicttostate
import time


def main():
    rospy.init_node('optitrack_replay')
    rospack = rospkg.RosPack()
    with open(rospack.get_path("human_moveit_config")+"/results/test3.json") as data_file:
        data = json.load(data_file)
    # loop through all the data
    iteration = 0

    human = HumanModel()

    start_time = time.time()
    while iteration < len(data['times']) and not rospy.is_shutdown():
        iter_time = time.time()
        rs = dicttostate(data['states'][iteration])
        human.send_state(rs.joint_state)
        diff_time = time.time() - iter_time
        if diff_time < data['times'][iteration]:
            rospy.sleep(diff_time)
        iteration += 1
    print 'total time: '+str(time.time()-start_time)

if __name__ == '__main__':
    main()
