#!/usr/bin/env python
from human_moveit_config.human_model import HumanModel
from sensor_link.sensor_calibrator import SensorCalibrator
from sensor_link.sensor_reader import SensorReader
import rospy
import rospkg
import json
import os
import sys
import tf


class Calibrator(object):
    def __init__(self):
        self.rospack = rospkg.RosPack()
        self.sensor_reader = SensorReader(False)
        self.sensor_calibr = SensorCalibrator()
        self.sensor_calibr.human = HumanModel()
        self.tfl = tf.TransformListener()
        rospy.sleep(1)

    def request_for_t_position(self, sensor, frames_list):
        # modify the list of visible frames
        if frames_list is list:
            self.sensor_reader.sensor_frames[sensor] = frames_list
        while not rospy.is_shutdown():
            rospy.sleep(10)
            os.system('beep')
            # raw_input("User in T position, press <Enter> when ready...")
            if self.sensor_reader.update_skeleton(sensor, debug=True):
                rospy.loginfo("T pose recorded successfully")
                break
            else:
                rospy.logerr("Cannot calibrate, skeleton not visible")
        # extract skeleton corresponding to sensor
        skel = self.sensor_reader.get_skeleton(sensor)
        # save the recorded T pose
        skeleton_file = self.rospack.get_path("human_moveit_config") + '/tmp/skeleton.json'
        # check already existing file
        if os.path.exists(skeleton_file):
            with open(skeleton_file) as data_file:
                skeletons = json.load(data_file)
            # overwrite only new value
            skeletons[sensor] = skel
        with open(skeleton_file, 'w') as output_file:
            json.dump(skeletons, output_file, sort_keys=True, indent=4)
        # return the recorded skeleton
        return skel

    def create_calibration_matrices(self, sensor, sensor_param, reset_pose):
        # read the config file with the selected frames
        frames_file = self.rospack.get_path("human_moveit_config") + '/config/frames_list.json'
        with open(frames_file) as data_file:
            data_frames = json.load(data_file)
        # check that parameter is correct
        if sensor_param not in data_frames[sensor].keys():
            rospy.logerr('Parameter unknown')
            sys.exit(1)
        frames_list = data_frames[sensor][sensor_param]
        # check if we need to record a new pose
        if reset_pose:
            # record a new T pose
            skeleton = self.request_for_t_position(sensor, frames_list)
        else:
            # otherwise use existing one
            skeleton_file = self.rospack.get_path("human_moveit_config") + '/tmp/skeleton.json'
            # read the T pose from human
            with open(skeleton_file) as data_file:
                skeleton = json.load(data_file)[sensor]
            if not skeleton:
                rospy.logwarn('No skeleton data were recorded. Record anyway')
                skeleton = self.request_for_t_position(sensor, frames_list)
        # for recorded skeleton calibrate the transformation matrices
        dict_calibr = {}
        # get ground axis
        ref = self.sensor_reader.sensors_ref[sensor] + '_frame'
        base_pose = self.tfl.lookupTransform(ref, 'base', rospy.Time(0))
        q = base_pose[1]
        z = [2 * (q[0] * q[2] + q[1] * q[3]),
             2 * (q[1] * q[2] - q[0] * q[3]),
             1 - 2 * q[0] * q[0] - 2 * q[1] * q[1]]
        x = [1 - 2 * q[1] * q[1] - 2 * q[2] * q[2],
             2 * (q[0] * q[1] + q[2] * q[3]),
             2 * (q[0] * q[2] - q[1] * q[3])]
        self.sensor_calibr.set_ground_axis(z)
        self.sensor_calibr.set_robot_axis(x)
        # if the file already exist load it to overwrite previous values
        calibration_file = self.rospack.get_path("human_moveit_config") + "/tmp/sensor_calibration.json"
        if os.path.exists(calibration_file):
            with open(calibration_file) as data_file:
                dict_calibr = json.load(data_file)
        # calibrate using optimization
        dict_calibr[sensor] = self.sensor_calibr.calibrate(skeleton, frames=frames_list)
        # write the calibration file
        with open(calibration_file, 'w') as output_file:
            json.dump(dict_calibr, output_file, sort_keys=True, indent=4)


if __name__ == '__main__':
    rospy.init_node('sensor_calibrator')
    calibrator = Calibrator()
    # create calibration matrices from human model
    calibrator.create_calibration_matrices(sys.argv[1], sys.argv[2], sys.argv[3] == 'True')
